import pandas as pd
import yfinance as yf
from datetime import datetime, timedelta
import os

def update_live_prices():
    # Calculate Indian Standard Time (UTC + 5:30)
    ist_now = datetime.utcnow() + timedelta(hours=5, minutes=30)
    print(f"\n--- Starting Live CMP Pinger at {ist_now.strftime('%H:%M:%S')} IST ---")
    
    try:
        # 1. Load the Top 20 list generated by Morning Master
        df = pd.read_csv("live_cmp.csv")
        
        # 2. Update CMP for those 20 stocks
        for index, row in df.iterrows():
            try:
                ticker = str(row['Stock Name']) + ".NS"
                # Fetching the very latest close price
                data = yf.Ticker(ticker).history(period="1d")
                if not data.empty:
                    live_price = round(data['Close'].iloc[-1], 2)
                    df.at[index, 'CMP'] = live_price
            except Exception: 
                pass # Skip if a specific ticker fails
        
        # 3. Update the timestamp in IST for Power BI
        df['Last updated'] = ist_now.strftime("%Y-%m-%d %H:%M")
        
        # 4. Save back to the same file
        df.to_csv("live_cmp.csv", index=False)
        print(f"Success! Live CMPs updated at {ist_now.strftime('%H:%M')} IST")
        
    except Exception as e:
        print(f"Error updating live prices: {e}")

if __name__ == "__main__":
    update_live_prices()
