name: Live CMP Updater

on:
  schedule:
    # 04:40 UTC = 10:10 AM IST (First Ping)
    - cron: '40 4 * * 1-5'
    
    # This handles 10:40, 11:10, 11:40, 12:10, 12:40, 13:10, 13:40, 14:10, 14:40, 15:10
    # UTC 05:10 to 09:40
    - cron: '10,40 5-9 * * 1-5'
    
    # 10:00 UTC = 03:30 PM IST (Final Closing Ping)
    - cron: '0 10 * * 1-5'

  workflow_dispatch: # Manual button

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install pandas yfinance
      - name: Run Live Pinger
        run: python live.py
      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git pull origin main --rebase
          git add live_cmp.csv
          git commit -m "Live Price Update" || echo "No changes"
          git push
